# Generated by Django 4.2.7 on 2026-03-09 05:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('must_change_password', models.BooleanField(default=False)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'db_table': 'pids_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('alert_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('source_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('destination_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('xgboost_score', models.FloatField(blank=True, null=True)),
                ('lightgbm_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(default='New', max_length=20)),
                ('resolved', models.BooleanField(default=False)),
                ('acknowledged_time', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pids_alert',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('admin', 'Administrator'), ('security_analyst', 'Security Analyst'), ('network_monitor', 'Network Monitor'), ('it_support', 'IT Support Staff'), ('ml_engineer', 'ML/AI Engineer')], max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('page_permissions', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'pids_role',
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('src_ip', models.CharField(db_index=True, max_length=45)),
                ('dst_ip', models.CharField(db_index=True, max_length=45)),
                ('src_port', models.IntegerField(default=0)),
                ('dst_port', models.IntegerField(default=0)),
                ('protocol', models.CharField(max_length=10)),
                ('length', models.IntegerField(default=0)),
                ('prediction', models.CharField(max_length=100)),
                ('confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Suspicious', 'Suspicious'), ('Attack', 'Attack')], db_index=True, max_length=20)),
                ('attack_type', models.CharField(blank=True, max_length=100, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('llm_analyzed', models.BooleanField(default=False)),
                ('llm_result', models.TextField(blank=True, null=True)),
                ('involves_local_pc', models.BooleanField(default=False)),
                ('is_zero_day', models.BooleanField(default=False)),
                ('used_for_training', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'pids_traffic_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['status', 'timestamp'], name='pids_traffi_status_0d1e79_idx'), models.Index(fields=['src_ip', 'timestamp'], name='pids_traffi_src_ip_890480_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThreatAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat_characterization', models.TextField()),
                ('attack_vectors', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('confidence', models.FloatField(default=0.0)),
                ('analysis_time', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='api.alert')),
            ],
            options={
                'db_table': 'pids_threat_analysis',
                'ordering': ['-analysis_time'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Custom', 'Custom'), ('Incident', 'Incident')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
                ('format', models.CharField(choices=[('PDF', 'PDF'), ('CSV', 'CSV'), ('JSON', 'JSON')], default='PDF', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('total_traffic', models.IntegerField(default=0)),
                ('total_attacks', models.IntegerField(default=0)),
                ('total_suspicious', models.IntegerField(default=0)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pids_report',
                'ordering': ['-generated_time'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_id', models.CharField(max_length=50, unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('false_positive_rate', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('training_data_count', models.IntegerField(default=0)),
                ('file_path', models.CharField(max_length=500)),
                ('trained_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trained_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pids_model_version',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('affected_entity', models.CharField(max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pids_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='traffic_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.trafficlog'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='api.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
