# Generated by Django 4.2.7 on 2026-03-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
