# Generated by Django 4.2.7 on 2026-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_avatar_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['status', 'prediction'], name='pids_traffi_status_b2e7ea_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['llm_analyzed'], name='pids_traffi_llm_ana_168139_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['used_for_training'], name='pids_traffi_used_fo_18a6bc_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['prediction', 'timestamp'], name='pids_traffi_predict_a8fe92_idx'),
        ),
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['-timestamp'], name='pids_traffi_timesta_43ad0c_idx'),
        ),
    ]
