# Generated by Django 4.2.7 on 2026-05-02 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_trafficlog_pids_traffi_status_b2e7ea_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_engine', models.CharField(choices=[('ml', 'ML (XGBoost + LightGBM)'), ('dl', 'DL (Two-Stage DNN)')], default='dl', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engine_config_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engine Configuration',
                'verbose_name_plural': 'Engine Configuration',
                'db_table': 'pids_engine_config',
            },
        ),
    ]
