# Generated by Django 4.2.7 on 2026-06-03 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_engineconfig_gnn_choice'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trafficlog',
            index=models.Index(fields=['is_zero_day'], name='pids_traffi_is_zero_0d6802_idx'),
        ),
    ]
